services:
  gateway:
    image: eak/eak-gateway-core:latest
    ports:
      - "8080:8080"
      - "8081:8081"

  postgres:
    image: postgres:15.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: rikkosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - ../../repository/docker/postgres:/docker-entrypoint-initdb.d

  flyway:
    image: flyway/flyway:9.14.1
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ../../schemas/migrations:/flyway/sql
      - ../../repository/docker/flyway:/flyway/conf
    depends_on:
      - postgres
