services:
  gateway:
    image: local/eak-gateway-core:latest
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      DATABASE_NAME: local_db
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: local_user
      DATABASE_PASSWORD: local_password

  postgres:
    image: postgres:17.5-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../backend/schemas/local/postgres:/docker-entrypoint-initdb.d

  flyway:
    image: flyway/flyway:12.0.0-alpine
    restart: on-failure
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -schemas=local_schema -connectRetries=60 migrate
    volumes:
      - ../backend/schemas/migrations:/flyway/sql
      - ../backend/schemas/local/flyway:/flyway/conf
    depends_on:
      - postgres