name: flyway-migration
on:
  workflow_call:
    inputs:
      module:
        description: "Module name"
        type: string
        required: true
      project-id:
        description: "Project ID (The environment you want to create resources in)"
        type: string
        required: true
      docker-build-directory:
        description: "Docker build directory"
        type: string
        required: true
      working-directory:
        description: "Working directory"
        type: string
        required: true
      environment:
        description: "Deployment environment name"
        type: string
        required: true
      docker-image-name:
        description: "Migration docker image name"
        type: string
        required: true
      docker-image-tag:
        description: "Migration docker image tag"
        type: string
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_do_token: ${{ secrets.DO_API_KEY }}
  TF_VAR_project_id: ${{ inputs.project-id }}
  TF_VAR_image_name: ${{ inputs.docker-image-name }}
  TF_VAR_image_tag: ${{ inputs.docker-image-tag }}
  DOCKER_BUILD_DIR: ${{ inputs.docker-build-directory }}
  DOCKER_REPOSITORY: ${{ vars.DOCKER_REPOSITORY }}
  DOCKER_IMAGE: ${{ vars.DOCKER_REPOSITORY }}/${{ inputs.docker-image-name }}:${{ inputs.docker-image-tag }}
jobs:
  build:
    environment: ${{ github.event_name == 'pull_request' && 'dev_pr' || inputs.environment || 'prod' }}
    name: flyway-migration ${{ inputs.module }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Build ${{ inputs.module }}
        run: docker build -t $DOCKER_IMAGE $DOCKER_BUILD_DIR
      - name: Publish Docker Image
        run: docker push $DOCKER_IMAGE
      - name: Terraform Init
        id: init
        run: |
          terraform -chdir=${{ inputs.working-directory }} init \
            -backend-config="bucket=${{ secrets.DO_SPACES_BUCKET }}" \
            -backend-config="key=${{ inputs.module }}-tf-state/terraform.tfstate" \
            -backend-config="endpoints={s3=\"https://${{ secrets.DO_SPACES_REGION }}.digitaloceanspaces.com\"}"
      - name: Terraform Apply
        run: terraform -chdir=${{ inputs.working-directory }} apply -auto-approve -input=false