name: scala-steward
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - name: Print Secret
        run: echo "SCALA_STEWARD_TOKEN ${{ secrets.SCALA_STEWARD_TOKEN }}"
      - name: Print Secret
        run: echo "SCALA_STEWARD_TOKEN ${{ secrets.SCALA_STEWARD_EMAIL }}"
      - name: Scala Steward GitHub Action
        uses: scala-steward-org/scala-steward-action@v2.75.0
        with:
          github-token: ${{ secrets.SCALA_STEWARD_TOKEN }}
          author-email: ${{ secrets.SCALA_STEWARD_EMAIL }}
